# Generated by Django 5.1.5 on 2025-01-16 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fats', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_meals', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.meal')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='food',
            field=models.ManyToManyField(related_name='meals', through='food.MealFood', to='food.food'),
        ),
    ]
