# Generated by Django 5.1.5 on 2025-01-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_food_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealfood',
            unique_together={('meal', 'food')},
        ),
    ]
