# Generated by Django 5.1.5 on 2025-01-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_food_options_alter_food_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ('order_number', 'meal_type')},
        ),
        migrations.AddField(
            model_name='meal',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, help_text='Optional: Specify the order for this meal type (e.g., 1 for breakfast, 2 for lunch).', null=True),
        ),
    ]
