# Generated by Django 5.1.5 on 2025-01-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_meal_options_meal_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodListTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fats', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='mealfood',
            options={'ordering': ('meal__order_number', 'meal__meal_type')},
        ),
    ]
